CREATE TABLE ZIPCODE_INFO
(
ZIP_CODE VARCHAR(5),
CITY VARCHAR(10)
);

CREATE TABLE INSTRUCTOR_INFO
(
INSTRUCTOR_ID NUMERIC(8,0),
INSTRUCTOR_FIRST_NAME VARCHAR(15),
INSTRUCTOR_LAST_NAME VARCHAR(15)
);

CREATE TABLE COURSE_INFO
(
COURSE_NO NUMERIC(8,0),
COST NUMERIC(5,2)
);

CREATE TABLE STUDENT_INFO
(
STUDENT_ID NUMERIC(8,0),
STUDENT_FIRST_NAME VARCHAR(15),
STUDENT_LAST_NAME VARCHAR(15)
);

CREATE TABLE SECTION_INFO
(
SECTION_ID NUMERIC(8,0),
COURSE_NO NUMERIC(8,0),
SECTION_NO NUMERIC(5),
INSTRUCTOR_ID NUMERIC(8,0)
);

CREATE TABLE ENROLLMENT_INFO
(
STUDENT_ID NUMERIC(8,0),
SECTION_ID NUMERIC(8,0)
);

CREATE TABLE GRADE_INFO
(
STUDENT_ID NUMERIC(8,0),
SECTION_ID NUMERIC(8,0),
GRADE_TYPE_CODE CHAR(2),
GRADE_CODE_OCCURANCE NUMERIC(5)
);

ALTER TABLE ZIPCODE_INFO
ALTER COLUMN CITY VARCHAR(25);

ALTER TABLE ZIPCODE_INFO
ADD STATE VARCHAR(2);

ALTER TABLE INSTRUCTOR_INFO
ALTER COLUMN INSTRUCTOR_FIRST_NAME VARCHAR(25);

ALTER TABLE INSTRUCTOR_INFO
ALTER COLUMN INSTRUCTOR_LAST_NAME VARCHAR(25);

ALTER TABLE INSTRUCTOR_INFO
ADD STREET_ADDRESS VARCHAR(50);

ALTER TABLE INSTRUCTOR_INFO
ADD ZIP_CODE VARCHAR(5);

ALTER TABLE COURSE_INFO
ADD COURSE_NAME VARCHAR(50);

ALTER TABLE COURSE_INFO
ADD COURSE_PREREQUISITE NUMERIC(8,0);

ALTER TABLE COURSE_INFO
ALTER COLUMN COST NUMERIC(9,2);

ALTER TABLE STUDENT_INFO
ALTER COLUMN STUDENT_FIRST_NAME VARCHAR(25);

ALTER TABLE STUDENT_INFO
ALTER COLUMN STUDENT_LAST_NAME VARCHAR(25);

ALTER TABLE STUDENT_INFO
ADD STREET_ADDRESS VARCHAR(50);

ALTER TABLE STUDENT_INFO
ADD ZIP_CODE VARCHAR(5);

ALTER TABLE SECTION_INFO
ALTER COLUMN SECTION_NO NUMERIC(3,0);

ALTER TABLE SECTION_INFO
ADD LOCATION VARCHAR(50);

ALTER TABLE SECTION_INFO
ADD CAPACITY NUMERIC(3,0);

ALTER TABLE ENROLLMENT_INFO
ADD ENROLLMENT_DATE DATE;

ALTER TABLE GRADE_INFO
ALTER COLUMN GRADE_CODE_OCCURANCE NUMERIC(38,0);

ALTER TABLE GRADE_INFO
ADD NUMERIC_GRADE NUMERIC(3,0);