CREATE TABLE PRODUCTS
(
PRODUCT_ID INT,
PRODUCT_NAME VARCHAR(50),
PRICE DECIMAL(10,2)
);

CREATE TABLE SALES
(
SALE_ID INT,
PRODUCT_ID INT,
QUANTITY INT
);

INSERT INTO PRODUCTS VALUES (1,'Laptop',60000);
INSERT INTO PRODUCTS VALUES (2,'Mouse',500);
INSERT INTO PRODUCTS VALUES (3,'Keyboard',1500);
INSERT INTO PRODUCTS VALUES (4,'Monitor',12000);
INSERT INTO PRODUCTS VALUES (5,'Printer',8000);

INSERT INTO SALES VALUES (101,1,2);
INSERT INTO SALES VALUES (102,2,5);
INSERT INTO SALES VALUES (103,1,1);
INSERT INTO SALES VALUES (104,3,3);

SELECT *
FROM PRODUCTS
WHERE PRODUCT_ID NOT IN
(
SELECT PRODUCT_ID FROM SALES
);