CREATE TABLE ORDERS
(
ORDER_ID INT,
ORDER_DATE DATE
);

CREATE TABLE ORDERITEMS
(
ITEM_ID INT,
ORDER_ID INT,
PRODUCT_NAME VARCHAR(50),
QUANTITY INT
);

INSERT INTO ORDERS VALUES (1,'2024-01-01');
INSERT INTO ORDERS VALUES (2,'2024-01-02');
INSERT INTO ORDERS VALUES (3,'2024-01-03');

INSERT INTO ORDERITEMS VALUES (101,1,'Laptop',1);
INSERT INTO ORDERITEMS VALUES (102,2,'Mouse',2);
INSERT INTO ORDERITEMS VALUES (103,4,'Keyboard',1);
INSERT INTO ORDERITEMS VALUES (104,5,'Monitor',1);

SELECT OI.*
FROM ORDERITEMS OI
LEFT JOIN ORDERS O
ON OI.ORDER_ID = O.ORDER_ID
WHERE O.ORDER_ID IS NULL;