CREATE TABLE ZIPCODE_INFO
(
ZIP_CODE VARCHAR(5),
CITY VARCHAR(25),
STATE VARCHAR(2)
);

CREATE TABLE INSTRUCTOR_INFO
(
INSTRUCTOR_ID NUMERIC(8,0),
INSTRUCTOR_FIRST_NAME VARCHAR(25),
INSTRUCTOR_LAST_NAME VARCHAR(25),
STREET_ADDRESS VARCHAR(50),
ZIP_CODE VARCHAR(5)
);

CREATE TABLE COURSE_INFO
(
COURSE_NO NUMERIC(8,0),
COURSE_NAME VARCHAR(50),
COURSE_PREREQUISITE NUMERIC(8,0),
COST NUMERIC(9,2)
);

CREATE TABLE STUDENT_INFO
(
STUDENT_ID NUMERIC(8,0),
STUDENT_FIRST_NAME VARCHAR(25),
STUDENT_LAST_NAME VARCHAR(25),
STREET_ADDRESS VARCHAR(50),
ZIP_CODE VARCHAR(5)
);

CREATE TABLE SECTION_INFO
(
SECTION_ID NUMERIC(8,0),
COURSE_NO NUMERIC(8,0),
SECTION_NO NUMERIC(3,0),
INSTRUCTOR_ID NUMERIC(8,0),
LOCATION VARCHAR(50),
CAPACITY NUMERIC(3,0)
);

CREATE TABLE ENROLLMENT_INFO
(
STUDENT_ID NUMERIC(8,0),
SECTION_ID NUMERIC(8,0),
ENROLLMENT_DATE DATE
);

CREATE TABLE GRADE_INFO
(
STUDENT_ID NUMERIC(8,0),
SECTION_ID NUMERIC(8,0),
GRADE_TYPE_CODE CHAR(2),
GRADE_CODE_OCCURANCE NUMERIC(38,0),
NUMERIC_GRADE NUMERIC(3,0)
);

INSERT INTO ZIPCODE_INFO VALUES ('10001','NewYork','NY');
INSERT INTO ZIPCODE_INFO VALUES ('20002','Washington','DC');

INSERT INTO INSTRUCTOR_INFO VALUES (1,'John','Smith','Street 1','10001');
INSERT INTO INSTRUCTOR_INFO VALUES (2,'David','Lee','Street 2','20002');

INSERT INTO COURSE_INFO VALUES (101,'Database',NULL,5000);
INSERT INTO COURSE_INFO VALUES (102,'Networking',101,4500);

INSERT INTO STUDENT_INFO VALUES (1,'Amit','Sharma','Street A','10001');
INSERT INTO STUDENT_INFO VALUES (2,'Rahul','Verma','Street B','20002');

INSERT INTO SECTION_INFO VALUES (1,101,1,1,'Room A',30);
INSERT INTO SECTION_INFO VALUES (2,102,1,2,'Room B',25);

INSERT INTO ENROLLMENT_INFO VALUES (1,1,'2024-01-10');
INSERT INTO ENROLLMENT_INFO VALUES (2,2,'2024-01-12');

INSERT INTO GRADE_INFO VALUES (1,1,'MT',1,85);
INSERT INTO GRADE_INFO VALUES (2,2,'FI',1,90);

ALTER TABLE ZIPCODE_INFO
ADD CONSTRAINT ZIP_PK PRIMARY KEY (ZIP_CODE);

ALTER TABLE ZIPCODE_INFO
ALTER COLUMN CITY VARCHAR(25) NOT NULL;

ALTER TABLE ZIPCODE_INFO
ALTER COLUMN STATE VARCHAR(2) NOT NULL;

ALTER TABLE INSTRUCTOR_INFO
ADD CONSTRAINT INSTRUCTOR_ID_PK PRIMARY KEY (INSTRUCTOR_ID);

ALTER TABLE INSTRUCTOR_INFO
ALTER COLUMN INSTRUCTOR_FIRST_NAME VARCHAR(25) NOT NULL;

ALTER TABLE INSTRUCTOR_INFO
ALTER COLUMN INSTRUCTOR_LAST_NAME VARCHAR(25) NOT NULL;

ALTER TABLE INSTRUCTOR_INFO
ADD CONSTRAINT ZIP_INSTRUCTOR_FK
FOREIGN KEY (ZIP_CODE) REFERENCES ZIPCODE_INFO(ZIP_CODE);

ALTER TABLE COURSE_INFO
ADD CONSTRAINT COURSE_NO_PK PRIMARY KEY (COURSE_NO);

ALTER TABLE COURSE_INFO
ALTER COLUMN COURSE_NAME VARCHAR(50) NOT NULL;

ALTER TABLE COURSE_INFO
ALTER COLUMN COST NUMERIC(9,2) NOT NULL;

ALTER TABLE STUDENT_INFO
ADD CONSTRAINT STUDENT_ID_PK PRIMARY KEY (STUDENT_ID);

ALTER TABLE STUDENT_INFO
ALTER COLUMN STUDENT_FIRST_NAME VARCHAR(25) NOT NULL;

ALTER TABLE STUDENT_INFO
ALTER COLUMN STUDENT_LAST_NAME VARCHAR(25) NOT NULL;

ALTER TABLE STUDENT_INFO
ADD CONSTRAINT ZIP_STUDENT_FK
FOREIGN KEY (ZIP_CODE) REFERENCES ZIPCODE_INFO(ZIP_CODE);

ALTER TABLE SECTION_INFO
ADD CONSTRAINT SECTION_ID_PK PRIMARY KEY (SECTION_ID);

ALTER TABLE SECTION_INFO
ALTER COLUMN SECTION_NO NUMERIC(3,0) NOT NULL;

ALTER TABLE SECTION_INFO
ADD CONSTRAINT COURSE_SECTION_FK
FOREIGN KEY (COURSE_NO) REFERENCES COURSE_INFO(COURSE_NO);

ALTER TABLE SECTION_INFO
ADD CONSTRAINT INSTRUCTOR_SECTION_FK
FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTOR_INFO(INSTRUCTOR_ID);

ALTER TABLE ENROLLMENT_INFO
ADD CONSTRAINT ENROLLMENT_STUD_SECT_PK
PRIMARY KEY (STUDENT_ID, SECTION_ID);

ALTER TABLE ENROLLMENT_INFO
ADD CONSTRAINT ENROLLMENT_STUDENT_ID_FK
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT_INFO(STUDENT_ID);

ALTER TABLE ENROLLMENT_INFO
ADD CONSTRAINT ENROLLMENT_SECTION_ID_FK
FOREIGN KEY (SECTION_ID) REFERENCES SECTION_INFO(SECTION_ID);

ALTER TABLE GRADE_INFO
ADD CONSTRAINT GRADE_STUD_SECT_TYPE_CODE_PK
PRIMARY KEY (STUDENT_ID, SECTION_ID, GRADE_TYPE_CODE, GRADE_CODE_OCCURANCE);

ALTER TABLE GRADE_INFO
ADD CONSTRAINT GRADE_STUDENT_ID_FK
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT_INFO(STUDENT_ID);

ALTER TABLE GRADE_INFO
ADD CONSTRAINT GRADE_SECTION_ID_FK
FOREIGN KEY (SECTION_ID) REFERENCES SECTION_INFO(SECTION_ID);

ALTER TABLE GRADE_INFO
ADD CONSTRAINT CHK_GRADE_TYPE_CODE
CHECK (GRADE_TYPE_CODE IN ('FI','HM','MT','PA','PJ','QZ'));

ALTER TABLE GRADE_INFO
ADD CONSTRAINT NUMERIC_GRADE_DEFAULT
DEFAULT 0 FOR NUMERIC_GRADE;