CREATE TABLE ZIPCODE_INFO(
ZIP_CODE VARCHAR(5),
CITY VARCHAR(25),
STATE VARCHAR(2)
);

CREATE TABLE INSTRUCTOR_INFO(
INSTRUCTOR_ID INT,
INSTRUCTOR_FIRST_NAME VARCHAR(25),
INSTRUCTOR_LAST_NAME VARCHAR(25),
STREET_ADDRESS VARCHAR(50),
ZIP_CODE VARCHAR(5)
);

CREATE TABLE COURSE_INFO(
COURSE_NO INT,
COURSE_NAME VARCHAR(50),
COURSE_PREREQUISITE INT,
COST DECIMAL(9,2)
);

CREATE TABLE STUDENT_INFO(
STUDENT_ID INT,
STUDENT_FIRST_NAME VARCHAR(25),
STUDENT_LAST_NAME VARCHAR(25),
STREET_ADDRESS VARCHAR(50),
ZIP_CODE VARCHAR(5)
);

CREATE TABLE SECTION_INFO(
SECTION_ID INT,
COURSE_NO INT,
SECTION_NO INT,
INSTRUCTOR_ID INT,
LOCATION VARCHAR(50),
CAPACITY INT
);

CREATE TABLE ENROLLMENT_INFO(
STUDENT_ID INT,
SECTION_ID INT,
ENROLLMENT_DATE DATE
);

CREATE TABLE GRADE_INFO(
STUDENT_ID INT,
SECTION_ID INT,
GRADE_TYPE_CODE CHAR(2),
GRADE_CODE_OCCURANCE INT,
NUMERIC_GRADE INT
);

INSERT INTO ZIPCODE_INFO VALUES ('10048','New York','NY');
INSERT INTO ZIPCODE_INFO VALUES ('11102','Queens','NY');
INSERT INTO ZIPCODE_INFO VALUES ('11209','Brooklyn','NY');
INSERT INTO ZIPCODE_INFO VALUES ('07001','Newark','NJ');

INSERT INTO INSTRUCTOR_INFO VALUES (1,'John','Schumer','Street 1','10048');
INSERT INTO INSTRUCTOR_INFO VALUES (2,'David','Miller','Street 2','11102');
INSERT INTO INSTRUCTOR_INFO VALUES (3,'Steve','Adams','Street 3','11209');

INSERT INTO COURSE_INFO VALUES (10,'Intro Database',NULL,4000);
INSERT INTO COURSE_INFO VALUES (20,'Intro Programming',10,4500);
INSERT INTO COURSE_INFO VALUES (30,'Networking Basics',20,6000);
INSERT INTO COURSE_INFO VALUES (40,'AI Intro',NULL,7000);

INSERT INTO STUDENT_INFO VALUES (300,'Amit','Graham','Addr1','10048');
INSERT INTO STUDENT_INFO VALUES (320,'Rahul','Sharma','Addr2','11102');
INSERT INTO STUDENT_INFO VALUES (340,'Sonia','Smith','Addr3','11209');

INSERT INTO SECTION_INFO VALUES (1,10,1,1,'Room A',30);
INSERT INTO SECTION_INFO VALUES (2,20,1,2,'Room B',25);

INSERT INTO ENROLLMENT_INFO VALUES (300,1,'1999-01-10');
INSERT INTO ENROLLMENT_INFO VALUES (320,2,'1999-01-15');

INSERT INTO GRADE_INFO VALUES (300,1,'FI',1,85);
INSERT INTO GRADE_INFO VALUES (320,2,'MT',1,75);

SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='COURSE_INFO';

SELECT ZIP_CODE,CITY,STATE AS STATE_NAME FROM ZIPCODE_INFO;

SELECT DISTINCT STATE FROM ZIPCODE_INFO;

SELECT STUDENT_ID,STUDENT_FIRST_NAME+' '+STUDENT_LAST_NAME AS NAME FROM STUDENT_INFO;

SELECT ZIP_CODE+', '+CITY+', '+STATE AS ADDRESS FROM ZIPCODE_INFO;

SELECT COURSE_NAME FROM COURSE_INFO;

SELECT COURSE_NAME,COST FROM COURSE_INFO;

SELECT * FROM COURSE_INFO;

SELECT INSTRUCTOR_LAST_NAME,ZIP_CODE FROM INSTRUCTOR_INFO;

SELECT DISTINCT ZIP_CODE FROM STUDENT_INFO;

SELECT STUDENT_FIRST_NAME,STUDENT_LAST_NAME FROM STUDENT_INFO;

SELECT CITY,STATE,ZIP_CODE FROM ZIPCODE_INFO;

SELECT STUDENT_ID,SECTION_ID,NUMERIC_GRADE FROM GRADE_INFO WHERE GRADE_TYPE_CODE='FI';

SELECT ZIP_CODE,CITY FROM ZIPCODE_INFO WHERE STATE='MI';

SELECT S.STUDENT_ID,S.STUDENT_FIRST_NAME+' '+S.STUDENT_LAST_NAME AS NAME
FROM STUDENT_INFO S
JOIN ENROLLMENT_INFO E ON S.STUDENT_ID=E.STUDENT_ID
WHERE MONTH(E.ENROLLMENT_DATE)=1 AND YEAR(E.ENROLLMENT_DATE)=1999
ORDER BY NAME;

SELECT SECTION_ID,INSTRUCTOR_ID FROM SECTION_INFO WHERE COURSE_NO IN (10,20) ORDER BY INSTRUCTOR_ID;

SELECT STUDENT_ID,SECTION_ID,NUMERIC_GRADE FROM GRADE_INFO ORDER BY SECTION_ID,NUMERIC_GRADE DESC;

SELECT COURSE_NO,COURSE_NAME,COST FROM COURSE_INFO WHERE COURSE_NAME LIKE '%Intro%';

SELECT * FROM COURSE_INFO WHERE COURSE_NAME LIKE '%a__';

SELECT STUDENT_FIRST_NAME,STUDENT_LAST_NAME FROM STUDENT_INFO WHERE STUDENT_ID BETWEEN 300 AND 350;

SELECT * FROM COURSE_INFO WHERE COST BETWEEN 4000 AND 7000;

SELECT INSTRUCTOR_FIRST_NAME FROM INSTRUCTOR_INFO WHERE INSTRUCTOR_LAST_NAME='Schumer';

SELECT INSTRUCTOR_FIRST_NAME FROM INSTRUCTOR_INFO WHERE INSTRUCTOR_LAST_NAME<>'Schumer';

SELECT COURSE_NAME,COST FROM COURSE_INFO WHERE COST>4000;

SELECT COURSE_NAME,COST FROM COURSE_INFO WHERE COST BETWEEN 3000 AND 7000;

SELECT COURSE_NAME,COST FROM COURSE_INFO WHERE COST IN (4000,4500);

SELECT STUDENT_FIRST_NAME,STREET_ADDRESS FROM STUDENT_INFO WHERE STUDENT_LAST_NAME LIKE 'S%';

SELECT STUDENT_FIRST_NAME,STREET_ADDRESS FROM STUDENT_INFO WHERE STUDENT_LAST_NAME LIKE '_o%';

SELECT INSTRUCTOR_FIRST_NAME FROM INSTRUCTOR_INFO WHERE INSTRUCTOR_LAST_NAME NOT LIKE 'S%';

SELECT COURSE_NAME,COST FROM COURSE_INFO WHERE COST BETWEEN 4000 AND 4500 AND COURSE_NAME LIKE 'I%';

SELECT COURSE_NAME,COST,COURSE_PREREQUISITE FROM COURSE_INFO WHERE (COST=2000 AND COURSE_PREREQUISITE=20) OR COURSE_PREREQUISITE=25;

SELECT COURSE_NAME,COST,COURSE_PREREQUISITE FROM COURSE_INFO WHERE COST=2000 OR COURSE_PREREQUISITE IN (20,25);

SELECT * FROM COURSE_INFO WHERE COURSE_PREREQUISITE IS NULL;

SELECT STUDENT_LAST_NAME FROM STUDENT_INFO WHERE ZIP_CODE IN ('10048','11102','11209');

SELECT INSTRUCTOR_FIRST_NAME,INSTRUCTOR_LAST_NAME FROM INSTRUCTOR_INFO WHERE LOWER(INSTRUCTOR_LAST_NAME) LIKE '%i%' AND ZIP_CODE='10025';

SELECT COURSE_NAME FROM COURSE_INFO WHERE COURSE_PREREQUISITE IS NOT NULL AND COST<1100;

SELECT DISTINCT COST FROM COURSE_INFO WHERE COURSE_PREREQUISITE IS NULL;

SELECT COURSE_NO,COURSE_NAME FROM COURSE_INFO WHERE COURSE_PREREQUISITE IS NULL ORDER BY COURSE_NAME;

SELECT COURSE_NO,COURSE_NAME FROM COURSE_INFO WHERE COURSE_PREREQUISITE IS NULL ORDER BY COURSE_NAME DESC;

SELECT CITY FROM ZIPCODE_INFO WHERE STATE IN ('NY','CT') ORDER BY ZIP_CODE;

SELECT ZIP_CODE,STUDENT_FIRST_NAME,STUDENT_LAST_NAME FROM STUDENT_INFO WHERE STUDENT_LAST_NAME='Graham' ORDER BY ZIP_CODE DESC,STUDENT_FIRST_NAME;

SELECT CITY+', '+STATE FROM ZIPCODE_INFO;

SELECT UPPER(LEFT(STUDENT_FIRST_NAME,1))+LOWER(SUBSTRING(STUDENT_FIRST_NAME,2,LEN(STUDENT_FIRST_NAME))) FROM STUDENT_INFO;

SELECT INSTRUCTOR_FIRST_NAME+', '+INSTRUCTOR_LAST_NAME FROM INSTRUCTOR_INFO;

SELECT COST,COST+10,COST-20,COST*30,COST/5 FROM COURSE_INFO;

SELECT DISTINCT NUMERIC_GRADE,CAST(NUMERIC_GRADE/2 AS INT) FROM GRADE_INFO;

SELECT FORMAT(COST,'N0') FROM COURSE_INFO WHERE COURSE_NO<25;

SELECT FORMAT(COST,'C2') FROM COURSE_INFO;

SELECT COURSE_NAME,ISNULL(CAST(COURSE_PREREQUISITE AS VARCHAR),'Not Applicable') FROM COURSE_INFO;

SELECT CITY,
CASE
WHEN STATE='NY' THEN 'New York'
WHEN STATE='NJ' THEN 'New Jersey'
ELSE 'Others'
END
FROM ZIPCODE_INFO;